title: Site

sections:
  pages:
    label: Content
    type: pages
    # sortBy: status asc
    image:
      query: false
      back: white
      color: black
  global:
    type: fields
    fields:
      line:
        type: line
      global_settings:
        label: Global Settings
        type: headline
      site_colors:
        label: Site colors
        type: object
        fields:
          background_color:
            label: Background Color
            type: color
            format: hsl
            width: 1/4
          primary_color:
            label: Primary Color
            type: color
            format: hsl
            width: 1/4
          secondary_color:
            label: Secondary Color
            type: color
            format: hsl
            width: 1/4
          tertiary_color:
            label: Tertiary Color
            type: color
            format: hsl
            width: 1/4
          gradient_color_a:
            label: Gradient Color A
            type: color
            format: hsl
            alpha: true
            width: 1/4
          gradient_color_b:
            label: Gradient Color B
            type: color
            format: hsl
            alpha: true
            width: 1/4
      navigation_order:
        label: Navigation Order
        type: multiselect
        options:
          type: query
          query: site.children.published
      footer:
        type: object
        fields:
          copyright:
            type: text
          email:
            type: email
          socials:
            type: list
            size: tiny
            nodes:
              - bulletList
            marks:
              - link

  


